/* 

Скрипт создания таблиц в БД модели
EAV/CR – Entity-Attribute-Value with Classes and Relationships 
(Сущность-Атрибут-Значение с Классами и Отношениями)."

 
create user devstr_eav IDENTIFIED BY d1234;
 
GRANT connect, resource to devstr_eav;


*/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE OBJREFERENCE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ATTRIBUTES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE OBJECTS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LISTS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ATTRTYPE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ATTRNAMES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE OBJTYPE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Таблица описаний объектных типов
CREATE TABLE OBJTYPE
  (
    OBJECT_TYPE_ID NUMBER(20),
    PARENT_ID      NUMBER(20),
    NAME           VARCHAR2(200 BYTE) NOT NULL UNIQUE,
    CONSTRAINT CON_OBJECT_TYPE_ID PRIMARY KEY (OBJECT_TYPE_ID),
    CONSTRAINT CON_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID) ON DELETE CASCADE
  );

-- Таблица имен атрибутов
CREATE TABLE ATTRNAMES
(
    ATTRN_ID      		NUMBER(20),
    NAME         		VARCHAR2(200 BYTE) NOT NULL UNIQUE,
	CONSTRAINT CON_ATTRN_ID PRIMARY KEY (ATTRN_ID)
);

-- Таблица описаний атрибутных типов
CREATE TABLE ATTRTYPE 
(
    OBJECT_TYPE_ID 		NUMBER(20) NOT NULL,
	OBJECT_TYPE_ID_REF  NUMBER(20),
	ATTRN_ID            NUMBER(20) NOT NULL,
    CONSTRAINT CON_ATTR_ID PRIMARY KEY (OBJECT_TYPE_ID, ATTRN_ID),
    CONSTRAINT CON_ATTR_OBJECT_TYPE_ID FOREIGN KEY (OBJECT_TYPE_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID),
	CONSTRAINT CON_ATTRNAME_ID FOREIGN KEY (ATTRN_ID) REFERENCES ATTRNAMES (ATTRN_ID)
);

-- Таблица для хранения листовых значений
CREATE TABLE LISTS
(
    LIST_VALUE_ID NUMBER(10),
    ATTRN_ID NUMBER(20) NOT NULL,
    VALUE VARCHAR2(4000) NOT NULL,
    CONSTRAINT CON_LIST_VALUE_ID PRIMARY KEY (LIST_VALUE_ID),
    CONSTRAINT CON_L_ATTR_ID FOREIGN KEY (ATTRN_ID) REFERENCES ATTRNAMES (ATTRN_ID) ON DELETE CASCADE
);

-- Таблица описаний экземпляров объектов
CREATE TABLE OBJECTS 
(
    OBJECT_ID      NUMBER(20),
    PARENT_ID      NUMBER(20),
    OBJECT_TYPE_ID NUMBER(20) NOT NULL,
    NAME           VARCHAR2(2000 BYTE),
    CONSTRAINT CON_OBJECTS_ID PRIMARY KEY (OBJECT_ID),
    CONSTRAINT CON_PARENTS_ID FOREIGN KEY (PARENT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE DEFERRABLE,
    CONSTRAINT CON_OBJ_TYPE_ID FOREIGN KEY (OBJECT_TYPE_ID) REFERENCES OBJTYPE (OBJECT_TYPE_ID)
);

-- Таблица описаний значений атрибутов экземпляров объектов
CREATE TABLE ATTRIBUTES
  (
    ATTRN_ID NUMBER(20) NOT NULL,
    OBJECT_ID NUMBER(20) NOT NULL,
    VALUE VARCHAR2(4000 byte),
    DATE_VALUE DATE,
    LIST_VALUE_ID NUMBER(10),
	CONSTRAINT CON_ATTRIBUTES_ID PRIMARY KEY (ATTRN_ID, OBJECT_ID),
    CONSTRAINT CON_ATR_LIST_VALUE_ID FOREIGN KEY (LIST_VALUE_ID) REFERENCES Lists (LIST_VALUE_ID) ON DELETE CASCADE,
    CONSTRAINT CON_ATR_NAME_ID FOREIGN KEY (ATTRN_ID) REFERENCES ATTRNAMES (ATTRN_ID) ON DELETE CASCADE,
    CONSTRAINT CON_ATR_OBJECT_ID FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE
  );  

-- Таблица описаний связей "простая ассоциация" между экземплярами объектов
CREATE TABLE OBJREFERENCE
  (
    ATTRN_ID        NUMBER(20) NOT NULL,
    REFERENCE       NUMBER(20) NOT NULL,
    OBJECT_ID       NUMBER(20) NOT NULL,
	CONSTRAINT CON_OBJREFERENCE_PK PRIMARY KEY (OBJECT_ID, ATTRN_ID, REFERENCE),
    CONSTRAINT CON_REFERENCE FOREIGN KEY (REFERENCE) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
    CONSTRAINT CON_ROBJECT_ID FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
    CONSTRAINT CON_RATTRN_ID FOREIGN KEY (ATTRN_ID) REFERENCES ATTRNAMES (ATTRN_ID) ON DELETE CASCADE
  );