BEGIN
   EXECUTE IMMEDIATE 'DROP INDEX obj_index1';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1418 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP INDEX obj_ref_index1';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1418 THEN
         RAISE;
      END IF;
END;
/

CREATE INDEX obj_index1 ON OBJECTS (OBJECT_TYPE_ID, NAME);
CREATE INDEX obj_ref_index1 ON OBJREFERENCE (REFERENCE, ATTRN_ID, OBJECT_ID);