 INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (1,1);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (1,2);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (1,3);

-- ListValue
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (1,4);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (1,5);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (1,6);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (1,7);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (2,5);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (2,8);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (2,7);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (2,9);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (2,10);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (2,11);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (2,12);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (2,13);
 
-- Нереференсные атрибуты сущности "Отзыв" 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (3,5);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (3,14);
 
 -- Нереференсные атрибуты сущности "Відгук на юзера"
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (4,15);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (4,16);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (4,17);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (5,18);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (5,19);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (5,20);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (5,21);
  
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (6,22);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID) -- reference project
 VALUES (6,2,28);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (6,24);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (1,4,25);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (2,1,26);

-- связь с отзывами
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (2,5,25);
 
 -- Референсные атрибуты сущности "Отзыв":
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (3,1,27);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (4,2,28);

-- Заполнение листовых значений:
-- Role
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4,'PROJECT_MANAGER');
 
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4,'TECHNICAL_MANAGER');

INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4,'GROUP_MANAGER');
 
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4, 'DEVELOPER');
 
 -- статус 
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (7, 'ACTIVE');

INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (7, 'INACTIVE');

--User role ADMIN
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4, 'ADMIN');
 
 COMMIT;