 INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (29,1);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (29,2);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (29,3);

-- ListValue
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (29,4);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (29,5);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (29,6);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (29,7);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,5);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,8);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,7);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,9);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,10);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,11);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,12);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,13);
 
-- Нереференсные атрибуты сущности "Отзыв" 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (31,5);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (31,14);
 
 -- Нереференсные атрибуты сущности "Відгук на юзера"
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (32,15);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (32,16);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (32,17);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (33,18);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (33,19);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (33,20);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (33,21);
  
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (34,22);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID) -- reference project
 VALUES (34,30,28);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (34,24);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (29,32,25);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (30,29,26);

-- связь с отзывами
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (30,33,25);
 
 -- Референсные атрибуты сущности "Отзыв":
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (31,29,27);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (32,30,28);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (29,30,28);

-- Заполнение листовых значений:
-- Role
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4,'PROJECT_MANAGER');
 
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4,'TECHNICAL_MANAGER');

INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4,'GROUP_MANAGER');
 
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4, 'DEVELOPER');
 
 -- статус 
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (7, 'ACTIVE');

INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (7, 'INACTIVE');

--User role ADMIN
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4, 'ADMIN');

 COMMIT;