INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,1);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,2);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,3);

-- ListValue
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,4);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,5);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,6);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (30,7);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (31,5);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (31,8);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (31,7);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (31,9);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (31,10);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (31,11);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (31,12);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (31,13);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (31,61);
 
-- Нереференсные атрибуты сущности "Отзыв" 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (32,5);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (32,14);
 
 -- Нереференсные атрибуты сущности "Відгук на юзера"
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (33,15);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (33,16);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (33,17);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (34,18);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (34,19);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (34,20);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (34,21);
  
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (35,22);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID) -- reference project
 VALUES (35,31,28);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,ATTRN_ID)
 VALUES (35,24);

INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (30,33,25);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (31,30,26);

-- связь с отзывами
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (31,34,25);
 
 -- Референсные атрибуты сущности "Отзыв":
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (32,30,27);
 
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (33,31,28);

--Reference from user to current project ID
INSERT INTO ATTRTYPE (OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,ATTRN_ID)
 VALUES (30,31,29);

-- Заполнение листовых значений:
-- Role
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4,'PROJECT_MANAGER');
 
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4,'TECHNICAL_MANAGER');

INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4,'GROUP_MANAGER');
 
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4, 'DEVELOPER');
 
 -- статус 
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (7, 'ACTIVE');

INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (7, 'INACTIVE');

--User role ADMIN
INSERT INTO LISTS (ATTRN_ID, VALUE)
 VALUES (4, 'ADMIN');
 
 COMMIT;