BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE log_id_seq';
EXCEPTION
    WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
    RAISE;
    END IF;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE LOGGER CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
    RAISE;
    END IF;
  END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE LOGGER_CONFIG CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
    RAISE;
    END IF;
  END;
/

create SEQUENCE log_id_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE LOGGER
(
LOG_ID         NUMBER(10),
MSG_LEVEL      VARCHAR2(200 CHAR),
MESSAGE        VARCHAR2(1999 CHAR),
LOG_DATE       DATE,
CONSTRAINT CON_LOG_ID PRIMARY KEY (LOG_ID)
);

create or replace trigger Trigger_log_id
BEFORE INSERT
  on LOGGER
for each row
begin
    select log_id_seq.nextval
    into :new.LOG_ID
    from dual;
end;
/

alter session set nls_date_format = 'dd/mm/yyyy hh24:mi:ss';

CREATE TABLE LOGGER_CONFIG
(
CONFIG_ID NUMBER(1) PRIMARY KEY,
C_NAME VARCHAR2(20 CHAR) NOT NULL,
C_VALUE VARCHAR2(2000)
);

INSERT INTO LOGGER_CONFIG(CONFIG_ID, C_NAME, C_VALUE) VALUES(1, 'LEVEL', 'INFO');
INSERT INTO LOGGER_CONFIG(CONFIG_ID, C_NAME, C_VALUE) VALUES(2, 'THRESHOLD', 2000);
INSERT INTO LOGGER_CONFIG(CONFIG_ID, C_NAME, C_VALUE) VALUES(3, 'SIZE', 0);
COMMIT;