BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE notification_id_seq';
EXCEPTION
    WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
    RAISE;
    END IF;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE NOTIFICATION CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
    RAISE;
    END IF;
  END;
/

CREATE SEQUENCE notification_id_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE NOTIFICATION
(
    NOTIFICATION_ID NUMBER(20) PRIMARY KEY,
	MESSAGE         VARCHAR2(2000 CHAR) NOT NULL,
	RECEIVER_ID     NUMBER(20) NOT NULL,
	CONSTRAINT REC_OBJ_CON FOREIGN KEY (RECEIVER_ID) REFERENCES OBJECTS(OBJECT_ID)
);

create or replace trigger Trigger_notification_id
BEFORE INSERT
  on NOTIFICATION
for each row
begin
    select notification_id_seq.nextval
    into :new.NOTIFICATION_ID
    from dual;
end;
/